# Sentiment thresholds (Peec returns 0-100)
SENTIMENT_POSITIVE_THRESHOLD = 60
SENTIMENT_NEGATIVE_THRESHOLD = 40

# Color palette (hex without #)
BRAND_FILL_COLOR = "152534"
ACCENT_FILL_COLOR = "F7BFD5"
CRITICAL_FILL = "FF6B6B"
WARNING_FILL = "FFD93D"
SUBTLE_GRAY = "F5F5F5"

# Limits
MAX_COOCCURRENCE_ROWS = 20
MAX_COMPETITORS_PER_BENCHMARK = 5
MAX_SOURCES_PER_GROUP = 10
CHAT_SNAPSHOT_CHARS = 300

# Peec API
PEEC_BASE_URL = "https://api.peec.ai/customer/v1"
PEEC_MAX_RETRIES = 3
PEEC_PAGE_SIZE = 100

# v1 platform filter — ChatGPT only
INCLUDED_PLATFORMS = ["ChatGPT"]
